# Generated by Django 4.1.1 on 2024-06-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_type', models.IntegerField(choices=[(10, 'Herb'), (20, 'Scroll'), (30, 'Bracelet'), (40, 'Jar'), (50, 'Staff')])),
                ('found', models.BooleanField(blank=True, default=False)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiren.price')),
            ],
        ),
    ]
