# Generated by Django 4.1.1 on 2022-11-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='buy_price',
            new_name='thing',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sell_price',
        ),
    ]
