# Generated by Django 4.1.1 on 2022-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0002_rename_buy_price_item_thing_remove_item_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thing',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='00', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='00', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sell_price',
            field=models.CharField(default='00', max_length=256),
            preserve_default=False,
        ),
    ]
