# Generated by Django 4.1.1 on 2022-11-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shiren.price'),
            preserve_default=False,
        ),
    ]
