# Generated by Django 4.1.1 on 2022-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0003_rename_thing_item_buy_price_item_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[(1, 'Herb'), (2, 'Scroll'), (3, 'Bracelet'), (4, 'Jar'), (5, 'Staff')], max_length=256),
        ),
    ]
