# Generated by Django 4.1.1 on 2022-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0004_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(10, 'Herb'), (20, 'Scroll'), (30, 'Bracelet'), (40, 'Jar'), (50, 'Staff')]),
        ),
    ]
