# Generated by Django 4.1.1 on 2022-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiren', '0005_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='found',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
